# Generated by Django 5.0.6 on 2024-06-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_testimonial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
